name: Build Artifacts
on:
  release:
    types: [published]
  workflow_dispatch:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
    
    - name: Build projects
      run: |
        export MAIN_DIR=$(pwd)
        cd ${GITHUB_WORKSPACE}
        chmod +x ./gradlew
        ./gradlew shadowJar
        cd ${MAIN_DIR}
        cp ${GITHUB_WORKSPACE}/paper/build/libs/paper-all.jar ./grakkit-paper.jar
    
    - name: Publish to GitHub Packages
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./grakkit-paper.jar